# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		nano blog
tagline:	'blog'
description:	'This is the official blog of nano.do'
url:		http://ortizjeison.github.io
commentsystem:	google
disqus:		camporez

author:
  name:		'nano team'
  url:		http://nano.do/about

paginate:	5

# Custom vars
icon:		/assets/images/icon22.png
cover:		/assets/images/cover2.png

social:
  - icon:	twitter
    url:	https://twitter.com/nanodo_en
    desc:	¡Follow us on twitter!

  - icon: facebook
    url:  https://twitter.com/nanodo_en
    desc: ¡Follow us on facebook!

#  - icon:	github
#    url:	https://github.com/camporez
#    desc:	Acesse meu github

#   - icon:	googleplus-alt
#    url:	https://google.com/+IanCamporezBrunelli
#    desc:	Me adicione ao google+

#  - icon:	feed
#    url:	http://camporez.github.io/atom.xml
#    desc:	Inscreva-se no meu feed
    
menu:
  - title:	Início
    url:	/
    
  - title:  Legal
    url:  /legal

  - title:	Legal
    url:	/legal


copyright:
  author:	Nano team
  url:		http://nano.do
  type_title:	nano 2018
  type_url:	http://creativecommons.org/licenses/by-nc/2.5/br
