# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		nano
tagline:	'blog'
description:	'This is the official blog of nano.do'
url:		https://nanoshort.github.io
commentsystem:	disqus
disqus:		nanodo-blog

author:
  name:		'nano team'
  url:		https://nano.do/about

paginate:	5

# Custom vars
icon:		/assets/images/icon22.png
cover:		/assets/images/cover2.png

social:
  - icon:	twitter
    url:	https://twitter.com/nanoshorten
    desc:	Follow us on twitter!

  - icon: facebook
    url:  https://www.facebook.com/nanoshorten
    desc: Follow us on facebook!

  - icon:	instagram
    url:	https://www.instagram.com/nanoshorten/
    desc:	Follow us on Instagram!

  - icon: chat
    url:  https://t.me/nanoshorten
    desc: Chat with us!

  - icon: link
    url:  https://nano.do/
    desc: Short your links.
    
menu:
  - title:	Home
    url:	/

  - title:  Legal
    url:  /legal

  - title:	Releases
    url:	/releases

  - title:  FAQ
    url:  /faq

copyright:
  author:	nano
  url:		http://nano.do
#  type_title:
  type_url:	http://creativecommons.org/licenses/by-nc/2.5/br
