# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		blogsito para probar
tagline:	'blog'
description:	'hola'
url:		http://ortizjeison.github.io
commentsystem:	google
disqus:		camporez

author:
  name:		'Ian Camporez Brunelli'
  url:		https://google.com/+IanCamporezBrunelli

paginate:	5

# Custom vars
icon:		/assets/images/icon2.png
cover:		/assets/images/cover2.png

social:
  - icon:	twitter
    url:	https://twitter.com/iancamporez
    desc:	Siga-me no twitter

  - icon:	github
    url:	https://github.com/camporez
    desc:	Acesse meu github

  - icon:	googleplus-alt
    url:	https://google.com/+IanCamporezBrunelli
    desc:	Me adicione ao google+

  - icon:	feed
    url:	http://camporez.github.io/atom.xml
    desc:	Inscreva-se no meu feed
    
menu:
  - title:	In√≠cio
    url:	/
    
  - title:	Sobre
    url:	/sobre


copyright:
  author:	Camporez
  url:		http://camporez.github.io
  type_title:	Alguns direitos reservados
  type_url:	http://creativecommons.org/licenses/by-nc/2.5/br
